-- 1. Tabelas independentes
INSERT INTO PAIS SELECT * FROM PF1788.PAIS;
COMMIT;
SELECT * FROM PAIS;
 
INSERT INTO TIPO_MOVIMENTO_ESTOQUE SELECT * FROM PF1788.TIPO_MOVIMENTO_ESTOQUE;
COMMIT;
SELECT * FROM TIPO_MOVIMENTO_ESTOQUE;

 
INSERT INTO TIPO_ENDERECO SELECT * FROM PF1788.TIPO_ENDERECO;
COMMIT;
SELECT * FROM TIPO_ENDERECO;

 
INSERT INTO USUARIO SELECT * FROM PF1788.USUARIO;
COMMIT;
SELECT * FROM USUARIO;
 
INSERT INTO VENDEDOR SELECT * FROM PF1788.VENDEDOR;
COMMIT;
SELECT * FROM VENDEDOR;

 
INSERT INTO CLIENTE SELECT * FROM PF1788.CLIENTE;
COMMIT;
SELECT * FROM CLIENTE;

 
INSERT INTO PRODUTO SELECT * FROM PF1788.PRODUTO;
COMMIT;
 
INSERT INTO ESTOQUE SELECT * FROM PF1788.ESTOQUE;
COMMIT;
 
-- 2. Tabelas com dependências de nível 2
INSERT INTO ESTADO SELECT * FROM PF1788.ESTADO;
COMMIT;
 
INSERT INTO CIDADE SELECT * FROM PF1788.CIDADE;
COMMIT;
 
INSERT INTO ENDERECO_CLIENTE SELECT * FROM PF1788.ENDERECO_CLIENTE;
COMMIT;
 
INSERT INTO CLIENTE_VENDEDOR SELECT * FROM PF1788.CLIENTE_VENDEDOR;
COMMIT;
 
INSERT INTO ESTOQUE_PRODUTO SELECT * FROM PF1788.ESTOQUE_PRODUTO;
COMMIT;
 
INSERT INTO PRODUTO_COMPOSTO SELECT * FROM PF1788.PRODUTO_COMPOSTO;
COMMIT;
 
-- 3. Tabela dependente de cliente, usuario, vendedor, endereco_cliente
INSERT INTO PEDIDO SELECT * FROM PF1788.PEDIDO;
COMMIT;
 
-- 4. Tabelas que dependem diretamente de pedido
INSERT INTO ITEM_PEDIDO SELECT * FROM PF1788.ITEM_PEDIDO;
COMMIT;
 
INSERT INTO HISTORICO_PEDIDO SELECT * FROM PF1788.HISTORICO_PEDIDO;
COMMIT;
 
-- 5. Por último, movimentação de estoque
INSERT INTO MOVIMENTO_ESTOQUE SELECT * FROM PF1788.MOVIMENTO_ESTOQUE;
COMMIT;