CREATE TABLE alunos (
    id_aluno NUMBER
        GENERATED BY DEFAULT AS IDENTITY
    PRIMARY KEY,
    nome     VARCHAR2(80) NOT NULL,
    idade    NUMBER(3)
);

CREATE OR REPLACE PACKAGE pkg_alunos AS
    PROCEDURE inserir_aluno (
        p_nome  VARCHAR2,
        p_idade NUMBER
    );

    PROCEDURE proc_listar_alunos;
    FUNCTION contar_alunos RETURN NUMBER;

END pkg_alunos;

CREATE OR REPLACE PACKAGE BODY pkg_alunos AS

    PROCEDURE inserir_aluno (
        p_nome  VARCHAR2,
        p_idade NUMBER
    ) IS
    BEGIN
        INSERT INTO alunos (
            nome,
            idade
        ) VALUES ( p_nome,
                   p_idade );

        COMMIT;
    END inserir_aluno;

    PROCEDURE proc_listar_alunos IS

        CURSOR c_alunos IS
        SELECT
            id_aluno,
            nome,
            idade
        FROM
            alunos
        ORDER BY
            id_aluno;

        v_id    alunos.id_aluno%TYPE;
        v_nome  alunos.nome%TYPE;
        v_idade alunos.idade%TYPE;
    BEGIN
        OPEN c_alunos;
        LOOP
            FETCH c_alunos INTO
                v_id,
                v_nome,
                v_idade;
            EXIT WHEN c_alunos%notfound;
            dbms_output.put_line('ID: '
                                 || v_id
                                 || ' | Nome: '
                                 || v_nome
                                 || ' | Idade: '
                                 || v_idade);

        END LOOP;

        CLOSE c_alunos;
    END proc_listar_alunos;

    FUNCTION contar_alunos RETURN NUMBER IS
        v_quantidade_alunos NUMBER;
    BEGIN
        SELECT
            COUNT(1)
        INTO v_quantidade_alunos
        FROM
            alunos;

        RETURN v_quantidade_alunos;
    END;

END pkg_alunos;

SET SERVEROUTPUT ON;

BEGIN
    pkg_alunos.inserir_aluno('Julia', 10);
    pkg_alunos.inserir_aluno('Fernando', 15);
    pkg_alunos.inserir_aluno('Luana', 29);
END;

BEGIN
    pkg_alunos.proc_listar_alunos;
END;

DECLARE
    v_contagem NUMBER;
BEGIN
    v_contagem := pkg_alunos.contar_alunos();
    dbms_output.put_line('Contagem dos alunos: ' || v_contagem);
END;

-- lista alunos com os cursores 
-- jeito do vergilio
    PROCEDURE listar_alunos IS
        CURSOR cur_alunos IS
        SELECT
            id_aluno,
            nome,
            idade
        FROM
            alunos
        ORDER BY
            id_aluno;

    BEGIN
        FOR x IN cur_alunos LOOP
            dbms_output.put_line('ID: '
                                 || x.id
                                 || ' | Nome: '
                                 || x.nome
                                 || ' | Idade: '
                                 || x.idade);
        END LOOP;
    END listar_alunos;