SELECT * FROM PAIS;
 
SELECT * FROM TIPO_MOVIMENTO_ESTOQUE;
 
SELECT * FROM TIPO_ENDERECO;
 
SELECT * FROM USUARIO;
 
SELECT * FROM VENDEDOR;
 
SELECT * FROM CLIENTE;
 
SELECT * FROM PRODUTO;
 
SELECT * FROM ESTOQUE;
 
SELECT * FROM ESTADO;
 
SELECT * FROM CIDADE;
 
SELECT * FROM ENDERECO_CLIENTE;
 
SELECT * FROM CLIENTE_VENDEDOR;
 
SELECT * FROM ESTOQUE_PRODUTO;
 
SELECT * FROM PRODUTO_COMPOSTO;
 
SELECT * FROM PEDIDO;
 
SELECT * FROM ITEM_PEDIDO;
 
SELECT * FROM HISTORICO_PEDIDO;
 
SELECT * FROM MOVIMENTO_ESTOQUE;